companies/urls.py
from django.conf.urls import url
from companies import views

app_name = 'companies'

urlpatterns = [
    url(r'^branches/(?P<by>[a-zA-Z_]*)$', views.branches_list, name='branches_list'),
    url(r'^delete/branch/(?P<pk>\d+)/$', views.delete_branch, name='delete_branch'),
    url(r'^edit/branch/(?P<pk>\d+)/$', views.edit_branch, name='edit_branch'),
    url(r'^departments/(?P<by>[a-zA-Z_]*)$', views.departments_list, name='departments_list'),
    url(r'^delete/department/(?P<pk>\d+)/$', views.delete_department, name='delete_department'),
    url(r'^edit/department/(?P<pk>\d+)/$', views.edit_department, name='edit_department'),
    url(r'^sections/(?P<by>[a-zA-Z_]*)$', views.sections_list, name='sections_list'),
    url(r'^delete/section/(?P<pk>\d+)/$', views.delete_section, name='delete_section'),
    url(r'^edit/section/(?P<pk>\d+)/$', views.edit_section, name='edit_section'),
    url(r'^sub_sections/(?P<by>[a-zA-Z_]*)$', views.sub_sections_list, name='sub_sections_list'),
    url(r'^delete/sub_section/(?P<pk>\d+)/$', views.delete_sub_section, name='delete_sub_section'),
    url(r'^edit/sub_section/(?P<pk>\d+)/$', views.edit_sub_section, name='edit_sub_section'),
    url(r'^degrees/(?P<by>[a-zA-Z_]*)$', views.degrees_list, name='degrees_list'),
    url(r'^delete/degree/(?P<pk>\d+)/$', views.delete_degree, name='delete_degree'),
    url(r'^edit/degree/(?P<pk>\d+)/$', views.edit_degree, name='edit_degree'),
    url(r'^settings/', views.settings, name='settings'),
]    

home/urls.py
from django.conf.urls import url
from home import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.landing, name='landing_page'),
    url(r'^dashboard/', views.dashboard, name='dashboard'),
    url(r'^login/', views.user_login, name='login'),
    url(r'^logout/', views.user_logout, name='logout'),
    
]

mashreq_hr_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from mashreq_hr_project import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls'), name="home"),
    url(r'^$', views.redirect, name='redirect'),
    url(r'^company/', include('companies.urls'), name='companies'),
    url(r'^employees/', include('employees.urls'), name='employees'),
    url(r'attendance/', include('attendance.urls'), name='attendance'),
    url(r'payroll/', include('payroll.urls'), name='payroll'),
    url(r'banks/', include('banks.urls'), name='banks'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Admin site global customizations
admin.site.site_header = 'Mashreq Arabia - HR'
admin.site.site_title = 'Mashreq Arabia - HR'

companies/forms.py
from django import forms
from django.core.exceptions import NON_FIELD_ERRORS 
from companies.models import Company, Branch, Department, Section, SubSection, Degree

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = '__all__'
        labels = {
            'name': 'اسم الشركة*',
        }
        error_messages = {
            'name': {
                'unique': "هذا الاسم مستخدم من قبل، برجاء اختيار اسم اخر",
            }
        }

class BranchForm(forms.ModelForm):
    class Meta:
        model = Branch
        fields = '__all__'
        labels = {
            'name': 'اسم الفرع*',
            'city_id': 'المدينة*',
        }
        widgets = {
            'company_id':forms.HiddenInput()
        }
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "يوجد فرع اخر مسجل بنفس الاسم!",
            }
        }

class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = '__all__'
        labels = {
            'name': 'اسم الادارة*',
            'branch_id': 'الفرع*',
        }
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "توجد ادارة اخرى بنفس الاسم مسجلة على نفس الفرع!",
            }
        }
    def __init__(self, company_id, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['branch_id'].queryset = Branch.objects.filter(company_id=company_id)
        
class SectionForm(forms.ModelForm):
    class Meta:
        model = Section
        fields = '__all__'
        labels = {
            'name': 'اسم القسم*',
            'department_id': 'الادارة*',
        }
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "يوجد قسم اخر بنفس الاسم مسجل على نفس الادارة!",
            }
        }
    def __init__(self, company_id, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['department_id'].queryset = Department.objects.filter(branch_id__company_id=company_id)

class SubSectionForm(forms.ModelForm):
    class Meta:
        model = SubSection
        fields = '__all__'
        labels = {
            'name': 'اسم الوظيفة*',
            'section_id': 'القسم*',
        }
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "توجد وظيفة اخرى بنفس الاسم مسجلة على نفس القسم!",
            }
        }
    def __init__(self, company_id, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['section_id'].queryset = Section.objects.filter(department_id__branch_id__company_id=company_id)

class DegreeForm(forms.ModelForm):
    class Meta:
        model = Degree
        fields = '__all__'
        labels = {
            'name': 'اسم الدرجة*',
            'sub_section_id': 'الوظيفة*',
        }
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "توجد درجة اخرى بنفس الاسم مسجلة على نفس الوظيفة!",
            }
        }
    def __init__(self, company_id, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['sub_section_id'].queryset = SubSection.objects.filter(section_id__department_id__branch_id__company_id=company_id)
        

companies/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from companies.models import Company, Branch, Department, Section, SubSection, Degree
from companies.forms import CompanyForm, BranchForm, DepartmentForm, SectionForm, SubSectionForm, DegreeForm
from django.http import HttpResponseForbidden
@login_required
def branches_list(request, by):
    if request.method == "POST":
        # Adding the company_id from the user model
        request.POST = request.POST.copy()  #converting the QueryDict to a mutable one
        request.POST['company_id'] = request.user.employee.company_id.pk
        form = BranchForm(request.POST)
        if form.is_valid():
            branch = form.save()
            success_msg = 'تم اضافة "{}" بنجاح'.format(branch.name)
            messages.success(request, success_msg)
            # Emptying the form before rerendering it back
            form = BranchForm()
        else: # Form was not valid
            # Spitting the errors coming from the form
            [messages.error(request, error[0]) for error in form.errors.values()]
        # Handling the "save and add another" button
        if 'save_and_add' in request.POST:
            save_and_add = True
        else:
            save_and_add = False
        context = {'table_title':'أفرع الشركة', 'modal_title':'اضافة فرع جديد', 'save_and_add':save_and_add, 'form':form}
    else:   # Request is GET
        # Just passing an empty form to be rendered in case of GET
        form = BranchForm()
        context = {'table_title':'أفرع الشركة', 'modal_title':'اضافة فرع جديد', 'form':form}
    try:    # Either GET or POST, We will render a table containing objects with company_id equals to user's company_id
        if by != '':
            branches = Branch.objects.filter(company_id=request.user.employee.company_id).order_by(by)
        else:
            branches = Branch.objects.filter(company_id=request.user.employee.company_id)
        context['branches'] = branches
    except: # Just in case the logged user is not tied to an employee account (i.e. doesn't have a company_id)
        messages.error(request, "لقد حدث خطأ ما، قد يكون هذا الحساب غير مسجل على شركة")
        context.pop('form')
    # Finally, and In all the cases, we will always render the same page to the user
    return render(request, 'companies/branches_list.html', context=context)

@login_required
def delete_branch(request, pk):
    try:
        branch = Branch.objects.get(pk=pk)
        if branch.company_id != request.user.employee.company_id:
            return HttpResponseForbidden("<h1>Access Denied! </h1>")
        if len(branch.departments.all()) == 0 and len(branch.employees.all()) == 0:
            branch.delete()
            success_msg = 'تم حذف "{}" بنجاح'.format(branch.name)
            messages.success(request, success_msg)
        else:
            error_msg = 'لا يمكن حذف "{}" لوجود بيانات أخرى مسجلة علية'.format(branch.name)
            messages.error(request, error_msg)
    except:
        error_msg = 'لم يتم الحذف المطلوب، خطأ ما قد حدث'
        messages.error(request, error_msg)
    return redirect('companies:branches_list', by='')

@login_required
def edit_branch(request, pk):
    try:
        branch = Branch.objects.get(pk=pk)
        if branch.company_id != request.user.employee.company_id:
            return HttpResponseForbidden("<h1>Access Denied! </h1>")
        if request.method == 'POST':
            form = BranchForm(request.POST, instance=branch)
            if form.is_valid():
                branch = form.save()
                success_msg = 'تم تعديل "{}" بنجاح'.format(branch.name)
                messages.success(request, success_msg)
            else: # Form was not valid
                # Spitting the errors coming from the form
                [messages.error(request, error[0]) for error in form.errors.values()]
        else: # request method is GET
            form = BranchForm(instance=branch)
            modal_close_url = 'companies:branches_list'
            context = {'table_title':'أفرع الشركة', 'modal_title':'تعديل بيانات الفرع', 'editing':True, 'modal_close_url':modal_close_url, 'form':form}
            try:
                branches = Branch.objects.filter(company_id=request.user.employee.company_id)
                context['branches'] = branches
            except: # Just in case the logged user is not tied to an employee account (i.e. doesn't have a company_id)
                messages.error(request, "لقد حدث خطأ ما، قد يكون هذا الحساب غير مسجل على شركة")
                context.pop('form')
            return render(request, 'companies/branches_list.html', context=context)
    except:
        error_msg = 'لم يتم العثور على البيان المطلوب، قد يكون قد تم حذفة من قبل'     
        messages.error(request, error_msg)
    return redirect('companies:branches_list', by='')

@login_required
def departments_list(request, by):
    if request.method == "POST":
        form = DepartmentForm(request.user.employee.company_id, request.POST)
        if form.is_valid():
            department = form.save()
            success_msg = 'تم اضافة "{}" بنجاح'.format(department.name)
            messages.success(request, success_msg)
            # Emptying the form before rerendering it back
            form = DepartmentForm(request.user.employee.company_id)
        else: # Form was not valid
            # Spitting the errors coming from the form
            [messages.error(request, error[0]) for error in form.errors.values()]
        # Handling the "save and add another" button
        if 'save_and_add' in request.POST:
            save_and_add = True
        else:
            save_and_add = False
        context = {'table_title':'الادارات', 'modal_title':'اضافة ادارة', 'save_and_add':save_and_add, 'form':form}
    else:   # Request is GET
        context = {'table_title':'الادارات', 'modal_title':'اضافة ادارة'}
        try:
            # Just passing an empty form to be rendered in case of GET
            form = DepartmentForm(request.user.employee.company_id)
            context['form'] = form
        except: # Just in case the logged user is not tied to an employee account (i.e. doesn't have a company_id)
            messages.error(request, "لقد حدث خطأ ما، قد يكون هذا الحساب غير مسجل على شركة")
    try:    # Either GET or POST, We will render a table containing objects with company_id equals to user's company_id
        if by != '':
            departments = Department.objects.filter(branch_id__company_id=request.user.employee.company_id).order_by(by)
        else:
            departments = Department.objects.filter(branch_id__company_id=request.user.employee.company_id)
        context['departments'] = departments
    except: # Just in case the logged user is not tied to an employee account (i.e. doesn't have a company_id)
        messages.error(request, "لقد حدث خطأ ما، قد يكون هذا الحساب غير مسجل على شركة")
    # Finally, and In all the cases, we will always render the same page to the user
    return render(request, 'companies/departments_list.html', context=context)

@login_required
def delete_department(request, pk):
    try:
        department = Department.objects.get(pk=pk)
        if department.branch_id.company_id != request.user.employee.company_id:
            return HttpResponseForbidden("<h1>Access Denied! </h1>")
        if len(department.employees.all()) == 0:
            department.delete()
            success_msg = 'تم حذف "{}" بنجاح'.format(department.name)
            messages.success(request, success_msg)
        else:
            error_msg = 'لا يمكن حذف "{}" لوجود بيانات أخرى مسجلة علية'.format(department.name)
            messages.error(request, error_msg)
    except:
        error_msg = 'لم يتم الحذف المطلوب، خطأ ما قد حدث'
        messages.error(request, error_msg)
    return redirect('companies:departments_list', by='')

@login_required
def edit_department(request, pk):
    try:
        department = Department.objects.get(pk=pk)
        if department.branch_id.company_id != request.user.employee.company_id:
            return HttpResponseForbidden("<h1>Access Denied! </h1>")
        if request.method == 'POST':
            form = DepartmentForm(request.user.employee.company_id, request.POST, instance=department)
            if form.is_valid():
                department = form.save()
                success_msg = 'تم تعديل "{}" بنجاح'.format(department.name)
                messages.success(request, success_msg)
            else: # Form was not valid
                # Spitting the errors coming from the form
                [messages.error(request, error[0]) for error in form.errors.values()]
        else: # request method is GET
            form = DepartmentForm(request.user.employee.company_id ,instance=department)
            modal_close_url = 'companies:departments_list'
            context = {'table_title':'الادارات', 'modal_title':'تعديل بيانات الادارة', 'editing':True, 'modal_close_url':modal_close_url, 'form':form}
            try:
                departments = Department.objects.filter(branch_id__company_id=request.user.employee.company_id)
                context['departments'] = departments
            except: # Just in case the logged user is not tied to an employee account (i.e. doesn't have a company_id)
                messages.error(request, "لقد حدث خطأ ما، قد يكون هذا الحساب غير مسجل على شركة")
                context.pop('form')
            return render(request, 'companies/departments_list.html', context=context)
    except:
        error_msg = 'لم يتم العثور على البيان المطلوب، قد يكون قد تم حذفة من قبل'     
        messages.error(request, error_msg)
    return redirect('companies:departments_list', by='')

@login_required
def sections_list(request, by):
    if request.method == "POST":
        form = SectionForm(request.user.employee.company_id, request.POST)
        if form.is_valid():

companies/templates/companies/degrees_list.html
{% extends "dashboard-viewdata.html" %}
{% load staticfiles %}
{% load extra_tags %}
{% block table %}
<table class="table table-hover table-sm">
        <thead>
            <tr>
                <th class="pr-4" scope="col">م</th>
                <th scope="col">
                <a href={% url 'companies:degrees_list' by='name' %} class="text-white">
                    اسم الدرجة
                </a>
                </th>
                <th scope="col">
                <a href={% url 'companies:degrees_list' by='sub_section_id__name' %} class="text-white">
                    الوظيفة التابعة لها
                    </a>
                </th>
                <th scope="col">
                        <a href={% url 'companies:degrees_list' by='sub_section_id__section_id__name' %} class="text-white">
                        القسم
                            </a>
                    </th>
                <th scope="col">
                        <a href={% url 'companies:degrees_list' by='sub_section_id__section_id__department_id__name' %} class="text-white">
                        الادارة
                        </a>
                </th>
                <th scope="col">
                        <a href={% url 'companies:degrees_list' by='sub_section_id__section_id__department_id__branch_id__name' %} class="text-white">
                        الفرع
                        </a>
                </th>
                <th scope="col">تعديل</th>
                <th scope="col">حذف</th>
            </tr>
        </thead>
        <tbody>
            {% for degree in degrees %}
            <tr class="table-light" id="table-row" >
                    <td class="pr-4" scope="row" data-toggle="modal" data-target="#detail-modal-{{degree.pk}}">
                        {{ forloop.counter }}
                    </td>
                    <td data-toggle="modal" data-target="#detail-modal-{{degree.pk}}">{{degree.name}}</td>
                    <td data-toggle="modal" data-target="#detail-modal-{{degree.pk}}">{{degree.sub_section_id|d_arrow_split}}</td>
                    <td data-toggle="modal" data-target="#detail-modal-{{degree.pk}}">{{degree.sub_section_id.section_id|d_arrow_split}}</td>
                    <td data-toggle="modal" data-target="#detail-modal-{{degree.pk}}">{{degree.sub_section_id.section_id.department_id|d_arrow_split}}</td>
                    <td data-toggle="modal" data-target="#detail-modal-{{degree.pk}}">{{degree.sub_section_id.section_id.department_id.branch_id|d_arrow_split}}</td>
                    <td> <a href={% url 'companies:edit_degree' pk=degree.pk %}><img src={% static 'img/edit-icon.png' %} alt="edit"></a></td>
                    <td>
                        <a href="#" data-toggle="modal" data-target="#delete-modal-{{degree.pk}}">
                            <img src={% static 'img/delete-icon.png' %} alt="delete">
                        </a>
                    </td>
                    
            </tr>
            <!--Detail Modal -->
            <div class="modal fade" id="detail-modal-{{degree.pk}}" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                <div class="modal-dialog modal modal-dialog-centered p-3" role="document">
                <div class="modal-content p-3">
                    <div class="modal-header">
                        <h3 class="modal-title" id="detailModalLabel">تفاصيل الدرجة:</h3>
                    </div>
                        <div id="detail-list" class="modal-body">
                            <ul class="list-group">
                                <li class="list-group-item list-group-item-primary d-flex justify-content-between align-items-center">
                                    اسم الدرجة:
                                    {{degree.name}}
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    الوظيفة التابعة لها:    
                                    {{degree.sub_section_id|d_arrow_split}}
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    القسم:    
                                    {{degree.sub_section_id.section_id|d_arrow_split}}
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    الادارة:    
                                    {{degree.sub_section_id.section_id.department_id|d_arrow_split}}
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    الفرع:    
                                    {{degree.sub_section_id.section_id.department_id.branch_id|d_arrow_split}}
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    عدد الموظفين الحاصلين على هذة الدرجة : 
                                    <span class="badge badge-primary badge-pill">{{degree.employees.all|length}}</span>
                                </li>
                            </ul>
                            <div id="detail-buttons">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                                    <a type="button" class="btn btn-primary" href={% url 'companies:edit_degree' pk=degree.pk %}>تعديل</a>
                                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete-modal-{{degree.pk}}">حذف</button>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="delete-modal-{{degree.pk}}" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                    <div class=" modal-dialog modal modal-dialog-centered w-50 p-3" role="document">
                    <div class="modal-content alert">
                        <div class="modal-header">
                            <h3 class="modal-title" id="detailModalLabel">هل أنت متأكد؟</h3>
                        </div>
                            <div class="modal-body">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                                    <a type="button" class="btn btn-danger" href={% url 'companies:delete_degree' pk=degree.pk %}>نعم، احذف</a>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
        </tbody>
    </table> 

{% endblock table %}

companies/templates/companies/sections_list.html
{% extends "dashboard-viewdata.html" %}
{% load staticfiles %}
{% load extra_tags %}
{% block table %}
<table class="table table-hover table-sm">
        <thead>
            <tr>
                <th class="pr-4" scope="col">م</th>
                <th scope="col">
                <a href={% url 'companies:sections_list' by='name' %} class="text-white">
                    اسم القسم
                </a>
                </th>
                <th scope="col">
                <a href={% url 'companies:sections_list' by='department_id__name' %} class="text-white">
                    الادارة التابع لها
                    </a>
                </th>
                <th scope="col">
                        <a href={% url 'companies:sections_list' by='department_id__branch_id__name' %} class="text-white">
                        الفرع   
                        </a>
                </th>
                <th scope="col">تعديل</th>
                <th scope="col">حذف</th>
            </tr>
        </thead>
        <tbody>
            {% for section in sections %}
            <tr class="table-light" id="table-row" >
                    <td class="pr-4" scope="row" data-toggle="modal" data-target="#detail-modal-{{section.pk}}">
                        {{ forloop.counter }}
                    </td>
                    <td data-toggle="modal" data-target="#detail-modal-{{section.pk}}">{{section.name}}</td>
                    <td data-toggle="modal" data-target="#detail-modal-{{section.pk}}">{{section.department_id|d_arrow_split}}</td>
                    <td data-toggle="modal" data-target="#detail-modal-{{section.pk}}">{{section.department_id.branch_id|d_arrow_split}}</td>
                    <td> <a href={% url 'companies:edit_section' pk=section.pk %}><img src={% static 'img/edit-icon.png' %} alt="edit"></a></td>
                    <td>
                        <a href="#" data-toggle="modal" data-target="#delete-modal-{{section.pk}}">
                            <img src={% static 'img/delete-icon.png' %} alt="delete">
                        </a>
                    </td>
                    
            </tr>
            <!--Detail Modal -->
            <div class="modal fade" id="detail-modal-{{section.pk}}" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                <div class="modal-dialog modal modal-dialog-centered p-3" role="document">
                <div class="modal-content p-3">
                    <div class="modal-header">
                        <h3 class="modal-title" id="detailModalLabel">تفاصيل القسم:</h3>
                    </div>
                        <div id="detail-list" class="modal-body">
                            <ul class="list-group">
                                <li class="list-group-item list-group-item-primary d-flex justify-content-between align-items-center">
                                    اسم القسم:
                                    {{section.name}}
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    الادارة التابع لها:    
                                    {{section.department_id|d_arrow_split}}
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                   عدد الوظائف الموجودة بالقسم:
                                    <span class="badge badge-primary badge-pill">{{section.subsections.all|length}}</span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    عدد الموظفين العاملين بالقسم: 
                                    <span class="badge badge-primary badge-pill">{{section.employees.all|length}}</span>
                                </li>
                            </ul>
                            <div id="detail-buttons">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                                    <a type="button" class="btn btn-primary" href={% url 'companies:edit_section' pk=section.pk %}>تعديل</a>
                                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete-modal-{{section.pk}}">حذف</button>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="delete-modal-{{section.pk}}" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                    <div class=" modal-dialog modal modal-dialog-centered w-50 p-3" role="document">
                    <div class="modal-content alert">
                        <div class="modal-header">
                            <h3 class="modal-title" id="detailModalLabel">هل أنت متأكد؟</h3>
                        </div>
                            <div class="modal-body">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                                    <a type="button" class="btn btn-danger" href={% url 'companies:delete_section' pk=section.pk %}>نعم، احذف</a>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
        </tbody>
    </table> 

{% endblock table %}

companies/templates/companies/settings.html
{% extends "dashboard.html" %}
{% load staticfiles %}
{% load bootstrap4 %}
{% block head2 %}
<link rel="stylesheet" href={% static "css/dashboard-viewdata.css" %}>
{% endblock head2 %}
{% block panel-body %}
<div class="container">
    <div class="row">
        <h1 class="col-lg-9 col-md-6 col-sm-12" id="title">اعدادات الشركة</h1>
        <div id="action-bar" class="col-lg-3 col-md-6 col-sm-12">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal">
                    <h4><img style="max-width:0.8em; max-width:0.8em;" src={% static 'img/edit-icon-white.png' %} alt="add">تغيير الاعدادات</h4>
                </button>
        </div>
    </div>
    <div class="row">
        <!-- displaying messages if there is any: -->
        <div class="col-lg-3"></div>
            {% if messages %}
            {% for message in messages %}
            {% if message.level == 25 %}
            <div class="alert alert-dismissible alert-success col-lg-6 col-md-12">
                {{ message }}
            </div>
            {% elif message.level == 40 %} 
        <div class="alert alert-dismissible alert-danger col-lg-6 col-md-12">
          {{ message }}
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}
        <!-- end of messages snippet -->
        </div>
        <div class="container">
            <div class="col-lg-6 col-sm-12">
                <ul class="list-group" style="box-shadow: 4px 4px 12px 0px rgba(36,58,81,0.42);background-color: #007bff;border-radius: 20px/12px;" >
                    <li class="list-group-item list-group-item-primary" style="border-radius: 0em;">اسم الشركة:</li>
                    <li class="list-group-item" style="border-radius: 0em;">{{ company.name }}</li>
                </ul>
            </div>
        </div>
    <!-- Modal -->
    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered p-3" role="document">
            <div class="modal-content p-3">
                <div class="modal-header">
                    <h2 class="modal-title" id="modalLabel">تغيير الاعدادات</h2>
                </div>
                <div class="modal-body">
                    {% if form %}
                    <form method="POST">
                        {% csrf_token %} 
                        {% bootstrap_form form %}
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                        <input type="submit" class="btn btn-success" value="حفظ" />
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock panel-body %}