banks/urls.py
from django.conf.urls import url
from banks import views

app_name = 'banks'

urlpatterns = [
    url(r'^banks/(?P<by>[a-zA-Z_]*)$', views.banks_list, name='banks_list'),
    url(r'^delete/bank/(?P<pk>\d+)/$', views.delete_bank, name='delete_bank'),
    url(r'^edit/bank/(?P<pk>\d+)/$', views.edit_bank, name='edit_bank'),
    url(r'^accounts/(?P<by>[a-zA-Z_]*)$', views.accounts_list, name='accounts_list'),
    url(r'^delete/account/(?P<pk>\d+)/$', views.delete_account, name='delete_account'),
    url(r'^edit/account/(?P<pk>\d+)/$', views.edit_account, name='edit_account'),
]    

companies/urls.py
from django.conf.urls import url
from companies import views

app_name = 'companies'

urlpatterns = [
    url(r'^branches/(?P<by>[a-zA-Z_]*)$', views.branches_list, name='branches_list'),
    url(r'^delete/branch/(?P<pk>\d+)/$', views.delete_branch, name='delete_branch'),
    url(r'^edit/branch/(?P<pk>\d+)/$', views.edit_branch, name='edit_branch'),
    url(r'^departments/(?P<by>[a-zA-Z_]*)$', views.departments_list, name='departments_list'),
    url(r'^delete/department/(?P<pk>\d+)/$', views.delete_department, name='delete_department'),
    url(r'^edit/department/(?P<pk>\d+)/$', views.edit_department, name='edit_department'),
    url(r'^sections/(?P<by>[a-zA-Z_]*)$', views.sections_list, name='sections_list'),
    url(r'^delete/section/(?P<pk>\d+)/$', views.delete_section, name='delete_section'),
    url(r'^edit/section/(?P<pk>\d+)/$', views.edit_section, name='edit_section'),
    url(r'^sub_sections/(?P<by>[a-zA-Z_]*)$', views.sub_sections_list, name='sub_sections_list'),
    url(r'^delete/sub_section/(?P<pk>\d+)/$', views.delete_sub_section, name='delete_sub_section'),
    url(r'^edit/sub_section/(?P<pk>\d+)/$', views.edit_sub_section, name='edit_sub_section'),
    url(r'^degrees/(?P<by>[a-zA-Z_]*)$', views.degrees_list, name='degrees_list'),
    url(r'^delete/degree/(?P<pk>\d+)/$', views.delete_degree, name='delete_degree'),
    url(r'^edit/degree/(?P<pk>\d+)/$', views.edit_degree, name='edit_degree'),
    url(r'^settings/', views.settings, name='settings'),
]    

employees/urls.py
from django.conf.urls import url
from employees import views

app_name = 'employees'

urlpatterns = [
    url(r'^employees/(?P<by>[a-zA-Z_]*)$', views.employees_list, name='employees_list'),
    url(r'^import_export/', views.employee_upload, name='import_export'),
    url(r'^imp/employees/', views.employee_upload , name='import_button'),
    url(r'^exp/employees/', views.export_data , name='export_button'),
    url(r'^edit/employee/(?P<pk>\d+)/$', views.edit_employee, name='edit_employee'),
    url(r'^disable/employee/(?P<pk>\d+)/$', views.disable_employee, name='disable_employee'),
    url(r'^contracts/(?P<by>[a-zA-Z_]*)$', views.contracts_list, name='contracts_list'),
    url(r'^edit/contract/(?P<pk>\d+)/$', views.edit_contract, name='edit_contract'),
    url(r'^delete/contract/(?P<pk>\d+)/$', views.delete_contract, name='delete_contract'),
    url(r'^id_documents/(?P<by>[a-zA-Z_]*)$', views.id_documents_list, name='id_documents_list'),
    url(r'^edit/id_document/(?P<pk>\d+)/$', views.edit_id_document, name='edit_id_document'),
    url(r'^delete/id_document/(?P<pk>\d+)/$', views.delete_id_document, name='delete_id_document'),
    url(r'^education_degrees/(?P<by>[a-zA-Z_]*)$', views.education_degrees_list, name='education_degrees_list'),
    url(r'^edit/education_degree/(?P<pk>\d+)/$', views.edit_education_degree, name='edit_education_degree'),
    url(r'^delete/education_degree/(?P<pk>\d+)/$', views.delete_education_degree, name='delete_education_degree'),
    url(r'^genders/(?P<by>[a-zA-Z_]*)$', views.genders_list, name='genders_list'),
    url(r'^edit/gender/(?P<pk>\d+)/$', views.edit_gender, name='edit_gender'),
    url(r'^delete/gender/(?P<pk>\d+)/$', views.delete_gender, name='delete_gender'),
    url(r'^social_status/(?P<by>[a-zA-Z_]*)$', views.social_status_list, name='social_status_list'),
    url(r'^edit/social_status/(?P<pk>\d+)/$', views.edit_social_status, name='edit_social_status'),
    url(r'^delete/social_status/(?P<pk>\d+)/$', views.delete_social_status, name='delete_social_status'),
    url(r'^military_status/(?P<by>[a-zA-Z_]*)$', views.military_status_list, name='military_status_list'),
    url(r'^edit/military_status/(?P<pk>\d+)/$', views.edit_military_status, name='edit_military_status'),
    url(r'^delete/military_status/(?P<pk>\d+)/$', views.delete_military_status, name='delete_military_status'),
    url(r'^religions/(?P<by>[a-zA-Z_]*)$', views.religions_list, name='religions_list'),
    url(r'^edit/religion/(?P<pk>\d+)/$', views.edit_religion, name='edit_religion'),
    url(r'^delete/religion/(?P<pk>\d+)/$', views.delete_religion, name='delete_religion'),
]

home/urls.py
from django.conf.urls import url
from home import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.landing, name='landing_page'),
    url(r'^dashboard/', views.dashboard, name='dashboard'),
    url(r'^login/', views.user_login, name='login'),
    url(r'^logout/', views.user_logout, name='logout'),
    
]

mashreq_hr_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from mashreq_hr_project import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls'), name="home"),
    url(r'^$', views.redirect, name='redirect'),
    url(r'^company/', include('companies.urls'), name='companies'),
    url(r'^employees/', include('employees.urls'), name='employees'),
    url(r'attendance/', include('attendance.urls'), name='attendance'),
    url(r'payroll/', include('payroll.urls'), name='payroll'),
    url(r'banks/', include('banks.urls'), name='banks'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Admin site global customizations
admin.site.site_header = 'Mashreq Arabia - HR'
admin.site.site_title = 'Mashreq Arabia - HR'

payroll/urls.py
from django.conf.urls import url
from payroll import views

app_name = 'payroll'

urlpatterns = [
    url(r'^salaries/(?P<by>[a-zA-Z_]*)$', views.salaries_list, name='salaries_list'),
    url(r'^delete/salary/(?P<pk>\d+)/$', views.delete_salary, name='delete_salary'),
    url(r'^edit/salary/(?P<pk>\d+)/$', views.edit_salary, name='edit_salary'),
    url(r'^finalize/salary/(?P<pk>\d+)/$', views.finalize_salary, name='finalize_salary'),
    url(r'^recalculate/salary/(?P<pk>\d+)/$', views.recalculate_salary, name='recalculate_salary'),
    url(r'^copy/salaries', views.copy_salaries, name='copy_salaries'),
    url(r'^send/payslips', views.send_payslips, name='send_payslips'),
    url(r'^salary_element_types/(?P<by>[a-zA-Z_]*)$', views.salary_element_types_list, name='salary_element_types_list'),
    url(r'^delete/salary_element_type/(?P<pk>\d+)/$', views.delete_salary_element_type, name='delete_salary_element_type'),
    url(r'^edit/salary_element_type/(?P<pk>\d+)/$', views.edit_salary_element_type, name='edit_salary_element_type'),
    url(r'^insurance_rules/(?P<by>[a-zA-Z_]*)$', views.insurance_rules_list, name='insurance_rules_list'),
    url(r'^delete/insurance_rule/(?P<pk>\d+)/$', views.delete_insurance_rule, name='delete_insurance_rule'),
    url(r'^edit/insurance_rule/(?P<pk>\d+)/$', views.edit_insurance_rule, name='edit_insurance_rule'),
    url(r'^custom_rules/(?P<by>[a-zA-Z_]*)$', views.custom_rules_list, name='custom_rules_list'),
    url(r'^delete/custom_rule/(?P<pk>\d+)/$', views.delete_custom_rule, name='delete_custom_rule'),
    url(r'^edit/custom_rule/(?P<pk>\d+)/$', views.edit_custom_rule, name='edit_custom_rule'),
    url(r'^tax_rules/(?P<by>[a-zA-Z_]*)$', views.tax_rules_list, name='tax_rules_list'),
    url(r'^delete/tax_rule/(?P<pk>\d+)/$', views.delete_tax_rule, name='delete_tax_rule'),
    url(r'^edit/tax_rule/(?P<pk>\d+)/$', views.edit_tax_rule, name='edit_tax_rule'),
]

mashreq_hr_project/views.py
from django.http import HttpResponseRedirect

def redirect(request):
    return HttpResponseRedirect('home')

mashreq_hr_project/templates/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Brython files goes here if required -->
    <script type="text/javascript" src={% static 'js/brython.js' %}></script>
    <!-- <script type="text/javascript" src={% static 'js/brython_stdlib.js' %}></script> -->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- custom css files goes here -->
    <!-- <link rel="stylesheet" href={% static 'css/base.css' %}> -->

    <!-- Custom fonts for this template-->
    <link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

    <!-- Page level plugin CSS-->
    <link href="/static/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="/static/css/sb-admin.css" rel="stylesheet">
    <!-- More custom css files inside the following blocks -->
    {% block head1 %}
    {% endblock head1 %}
    {% block head2 %}
    {% endblock head2 %}
    <!-- fonts goes here -->
    <!-- <link href="https://fonts.googleapis.com/css?family=Lateef&amp;subset=arabic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lalezar&amp;subset=arabic" rel="stylesheet"> -->

    <title>Moratabaty.com</title>
</head>

<body onload="brython(1)" id="page-top">

  <div>
    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
      <i class="fas fa-bars"></i>
    </button>
    <a class="navbar-brand mr-1" href={% url 'home:landing_page' %}>مرتباتي</a>

    <!-- Navbar Search -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>
    <h6><font color="white">مرحباً {{user.username}}</font></h6>
    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-0">
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-bell fa-fw"></i>
          <!-- <span class="badge badge-danger">9+</span> -->
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-envelope fa-fw"></i>
          <!-- <span class="badge badge-danger">7</span> -->
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle fa-fw"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href={% url 'home:landing_page' %}>مرتباتي</a>
          <a class="dropdown-item" href={% url 'home:dashboard' %}>لوحة التحكم</a>
          <!-- <a class="dropdown-item" href="#">مرحباً {{user.username}}</a> -->
          <div class="dropdown-divider"></div>
          <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">تسجيل الخروج</a>
            {% else %}
                <a class="dropdown-item" href={% url 'home:login'  %}>تسجيل الدخول</a>
            {% endif %}
            </ul>
          <!-- <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">تسجيل الخروج</a> -->
        </div>
      </li>
    </ul>
  </nav>
  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" >
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">مستـــعد للمغـــادرة؟</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">هل انت متأكد من الخروج</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">الغـــاء</button>
          <a class="btn btn-primary" href={% url 'home:logout' %}>خـــروج</a>
        </div>
      </div>
    </div>
  </div>
  <div id="wrapper">
  <!-- Sidebar -->
  <ul class="sidebar navbar-nav">
    <li class="nav-item active" >
      <a class="nav-link" href={% url 'home:dashboard' %}>
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>لــوحة التحكم</span>
      </a>
    </li>
    <!-- sidebar company menu -->
    <li class="nav-item dropdown">
      <a  class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-building"></i>
        <span>الشركة</span>
      </a>
      <div class="dropdown-menu" aria-labelledby="company">
        <a class="dropdown-item" href="{% url 'companies:settings' %}">اعدادات الشركة</a>
        <a class="dropdown-item" href={% url 'companies:branches_list' by='' %}>الأفرع</a>
        <a class="dropdown-item" href={% url 'companies:departments_list' by='' %}>الأدارات</a>
        <!-- <div class="dropdown-divider"></div> -->
        <!-- <h6 class="dropdown-header" href="404.html">الأقسام</h6> -->
        <a class="dropdown-item" href={% url 'companies:sections_list' by='' %}>الأقســام</a>
        <a class="dropdown-item" href={% url 'companies:sub_sections_list' by='' %}>الوظائف</a>
        <a class="dropdown-item" href={% url 'companies:degrees_list' by='' %}>الدرجات</a>
      </div>
    </li>

    <!-- sidebar Banks menu -->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="bank" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-university"></i>
        <span>البنوك</span>
      </a>
      <div class="dropdown-menu" aria-labelledby="pagesDropdown">
        <a class="dropdown-item" href="{% url 'banks:banks_list' by='' %}">البنوك</a>
        <a class="dropdown-item" href="{% url 'banks:accounts_list' by='' %}">الحسابات</a>
      </div>
    </li>

    <!-- sidebar Employees menu -->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="employee" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-users"></i>
        <span>المـوظفين</span>
      </a>
      <div class="dropdown-menu" aria-labelledby="pagesDropdown">
        <a class="dropdown-item" href="{% url 'employees:employees_list' by='' %}">عرض الموظفين</a>
        <h6 class="dropdown-header">اعدادات الموظفين</h6>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{% url 'employees:contracts_list' by='' %}">انواع التعاقدات</a>
        <a class="dropdown-item" href="{% url 'employees:id_documents_list' by='' %}">أنواع وثائق الهوية</a>
        <a class="dropdown-item" href="{% url 'employees:education_degrees_list' by='' %}">الدرجات التعليمية</a>
        <a class="dropdown-item" href="{% url 'employees:genders_list' by='' %}">انواع الموظفين</a>
        <a class="dropdown-item" href="{% url 'employees:social_status_list' by='' %}">الحالة الأجتماعية</a>
        <a class="dropdown-item" href="{% url 'employees:military_status_list' by='' %}">الموقف من التجنيد</a>
        <a class="dropdown-item" href="{% url 'employees:religions_list' by='' %}">الديانات</a>
        <h6 class="dropdown-header">ادراج من ملف اكسيل</h6>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href={% url 'employees:import_export' %}>ادراج</a>
      </div>
    </li>

    <!-- sidebar Attendance menu -->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="attendance" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-concierge-bell"></i>
        <span>الحضور</span>
      </a>
      <div class="dropdown-menu" aria-labelledby="pagesDropdown">
        <a class="dropdown-item" href="{% url 'attendance:attendance_settings' by='' %}">الحضور</a>
        <a class="dropdown-item" href="{% url 'attendance:attendance_settings' by='' %}">اعدادات الحضور</a>
      </div>
    </li>

    <!-- sidebar payroll menu -->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="payroll" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-hand-holding-usd"></i>
        <span>المرتبات</span>
      </a>
      <div class="dropdown-menu" aria-labelledby="pagesDropdown">
        <h6 class="dropdown-header">اعدادات المرتب</h6>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{% url 'payroll:salary_element_types_list' by='' %}">انواع بنود المرتب</a>
        <a class="dropdown-item" href="{% url 'payroll:insurance_rules_list' by='' %}">قواعد احتساب التأمينات </a>
        <a class="dropdown-item" href="{% url 'payroll:tax_rules_list' by='' %}">قواعد احتساب الضريبة </a>
        <a class="dropdown-item" href="{% url 'payroll:custom_rules_list' by='' %}">قواعد احتساب مخصصات </a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href={% url 'payroll:salaries_list' by='' %}>المرتبات</a>
        <a class="dropdown-item" href={% url 'payroll:copy_salaries' %}>انشاء سريع من<br>مرتبات شهر سابق</a>
        <a class="dropdown-item" href={% url 'payroll:send_payslips' %}>ارسال قسائم القبض</a>
      </div>
    </li>

  </ul>

  <div id="content-wrapper">
    <div class="container-fluid">
      {% block body %}
      {% endblock body %}
    </div>
  </div>
  </div>
</div>
  <!-- /.container-fluid -->

    <!-- Bootstrap core JavaScript-->
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Page level plugin JavaScript-->
    <script src="/static/vendor/chart.js/Chart.min.js"></script>
    <script src="/static/vendor/datatables/jquery.dataTables.js"></script>
    <script src="/static/vendor/datatables/dataTables.bootstrap4.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="/static/js/sb-admin.min.js"></script>

    <!-- Demo scripts for this page-->
    <script src="/static/js/demo/datatables-demo.js"></script>
    <script src="/static/js/demo/chart-area-demo.js"></script>


</body>
</html>

mashreq_hr_project/templates/dashboard-viewdata.html
{% extends "dashboard.html" %}
{% load bootstrap4 %}
{% load staticfiles %}
{% block head2 %}
<link rel="stylesheet" href={% static "css/dashboard-viewdata.css" %}>
{% endblock head2 %}
{% block panel-body %}

<!-- Inserting a dummy variable that will be detected by brython in case of clicking "save and add button" or in case we are editing the record -->
{% if save_and_add or editing %}
<div id="open-modal"></div>
{% endif %}
<div class="row">
    <h1 id="title">{{ table_title }}</h1>
    <div>
        <button type="button" class="button button5" data-toggle="modal" data-target="#modal">
            <h4 class="fa fa-plus-square"> اضافة بيان جديد</h4>

        </button>
    </div>
  </div>


    {% if not save_and_add %}
    <!-- displaying messages if there is any: -->
    {% if messages %}
    <div class="row">
    {% for message in messages %}
        <div class="col-lg-3"></div>
        {% if message.level == 25 %}
        <div class="alert alert-dismissible alert-success col-lg-6 col-md-12">
            {{ message }}
        </div>
        {% elif message.level == 40 %}
    <div class="alert alert-dismissible alert-danger col-lg-6 col-md-12">
      {{ message }}
    </div>
    {% endif %}
    <div class="col-lg-3"></div>
    {% endfor %}
</div>
    {% endif %}
    <!-- end of messages snippet -->
    {% endif %}
    <div class="table-responsive">
            {% block table %}

            {% endblock table %}
    </div>
    <!-- Modal -->
    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered p-3" role="document">
            <div class="modal-content p-3">
                <div class="modal-header">
                    <h2 class="modal-title" id="modalLabel">{{ modal_title }}</h2>
                </div>
                <div class="modal-body">
                {% if save_and_add %}
                <!-- displaying messages if there is any: -->
                    {% if messages %}
                    {% for message in messages %}
                    {% if message.level == 25 %}
                    <div class="alert alert-dismissible alert-success" style="display: block;">
                        {{ message }}
                    </div>
                        {% endif %}
                        {% endfor %}
                        {% endif %}
                <!-- end of messages snippet -->
                {% endif %}
                    {% if form %}
                    <form enctype="multipart/form-data" method="POST">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        {% if formset %}
                        <div id="formset" class="card mb-2 p-3">
                            {{formset_title}}
                            <div class="card-body">
                                {{ formset.management_form }}
                                {% for form in formset  %}
                                <div id="form-{{forloop.counter}}" class="card m-2 p-4">
                                        {% bootstrap_form form layout='horizontal' %}
                                </div>
                                {% endfor %}
                            </div>
                            <div class="container">
                                <div class="row">
                                    <div class="col-lg-8"></div>
                                    <div class="col-lg-4 col-md-12" >
                                        <button id="add-row-btn" type="button" class="btn btn-warning btn-block">اضافة صف</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% if editing %}
                        <a type="button" class="btn btn-secondary" href={% url modal_close_url by='' %}>رجوع</a>
                        <input type="submit" class="btn btn-success" value="حفظ التعديلات" />
                        {% else %}
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                        <input type="submit" class="btn btn-success" value="حفظ" />
                        <input name="save_and_add" type="submit" class="btn btn-primary" value="حفظ و اضافة بيان اخر"/>
                        {% endif %}
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock panel-body %}

mashreq_hr_project/templates/dashboard.html
{% extends "base.html" %}
{% load staticfiles %}
<!-- {% block head1 %}
<link rel="stylesheet" href={% static 'css/dashboard.css' %}>
{% endblock head1 %}  -->

{% block body %}

{% block panel-body %}
{% endblock panel-body %}

<!-- <script type="text/python" src={% static 'py/mashreq_hr_project.py' %}> -->
{% endblock body %}