employees/urls.py
from django.conf.urls import url
from employees import views

app_name = 'employees'

urlpatterns = [
    url(r'^employees/(?P<by>[a-zA-Z_]*)$', views.employees_list, name='employees_list'),
    url(r'^import_export/', views.employee_upload, name='import_export'),
    url(r'^imp/employees/', views.employee_upload , name='import_button'),
    url(r'^exp/employees/', views.export_data , name='export_button'),
    url(r'^edit/employee/(?P<pk>\d+)/$', views.edit_employee, name='edit_employee'),
    url(r'^disable/employee/(?P<pk>\d+)/$', views.disable_employee, name='disable_employee'),
    url(r'^contracts/(?P<by>[a-zA-Z_]*)$', views.contracts_list, name='contracts_list'),
    url(r'^edit/contract/(?P<pk>\d+)/$', views.edit_contract, name='edit_contract'),
    url(r'^delete/contract/(?P<pk>\d+)/$', views.delete_contract, name='delete_contract'),
    url(r'^id_documents/(?P<by>[a-zA-Z_]*)$', views.id_documents_list, name='id_documents_list'),
    url(r'^edit/id_document/(?P<pk>\d+)/$', views.edit_id_document, name='edit_id_document'),
    url(r'^delete/id_document/(?P<pk>\d+)/$', views.delete_id_document, name='delete_id_document'),
    url(r'^education_degrees/(?P<by>[a-zA-Z_]*)$', views.education_degrees_list, name='education_degrees_list'),
    url(r'^edit/education_degree/(?P<pk>\d+)/$', views.edit_education_degree, name='edit_education_degree'),
    url(r'^delete/education_degree/(?P<pk>\d+)/$', views.delete_education_degree, name='delete_education_degree'),
    url(r'^genders/(?P<by>[a-zA-Z_]*)$', views.genders_list, name='genders_list'),
    url(r'^edit/gender/(?P<pk>\d+)/$', views.edit_gender, name='edit_gender'),
    url(r'^delete/gender/(?P<pk>\d+)/$', views.delete_gender, name='delete_gender'),
    url(r'^social_status/(?P<by>[a-zA-Z_]*)$', views.social_status_list, name='social_status_list'),
    url(r'^edit/social_status/(?P<pk>\d+)/$', views.edit_social_status, name='edit_social_status'),
    url(r'^delete/social_status/(?P<pk>\d+)/$', views.delete_social_status, name='delete_social_status'),
    url(r'^military_status/(?P<by>[a-zA-Z_]*)$', views.military_status_list, name='military_status_list'),
    url(r'^edit/military_status/(?P<pk>\d+)/$', views.edit_military_status, name='edit_military_status'),
    url(r'^delete/military_status/(?P<pk>\d+)/$', views.delete_military_status, name='delete_military_status'),
    url(r'^religions/(?P<by>[a-zA-Z_]*)$', views.religions_list, name='religions_list'),
    url(r'^edit/religion/(?P<pk>\d+)/$', views.edit_religion, name='edit_religion'),
    url(r'^delete/religion/(?P<pk>\d+)/$', views.delete_religion, name='delete_religion'),
]

home/urls.py
from django.conf.urls import url
from home import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.landing, name='landing_page'),
    url(r'^dashboard/', views.dashboard, name='dashboard'),
    url(r'^login/', views.user_login, name='login'),
    url(r'^logout/', views.user_logout, name='logout'),
    
]

mashreq_hr_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from mashreq_hr_project import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls'), name="home"),
    url(r'^$', views.redirect, name='redirect'),
    url(r'^company/', include('companies.urls'), name='companies'),
    url(r'^employees/', include('employees.urls'), name='employees'),
    url(r'attendance/', include('attendance.urls'), name='attendance'),
    url(r'payroll/', include('payroll.urls'), name='payroll'),
    url(r'banks/', include('banks.urls'), name='banks'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Admin site global customizations
admin.site.site_header = 'Mashreq Arabia - HR'
admin.site.site_title = 'Mashreq Arabia - HR'

employees/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from employees.models import (Employee, Contract, IdDocument,
                              EducationDegree, Gender, SocialStatus,
                              MilitaryStatus, Religion)
from employees.forms import (EmployeeForm, ContractForm, IdDocumentForm,
                             EducationDegreeForm, GenderForm, SocialStatusForm,
                             MilitaryStatusForm, ReligionForm)
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponseForbidden
from employees.resources import EmployeeResources
from django.http import HttpResponse
from tablib import Dataset
from django.utils.datastructures import MultiValueDictKeyError
import xlrd


@login_required
def employees_list(request, by):
    if request.method == "POST":
        # Adding the company_id from the user model
        request.POST = request.POST.copy()  #converting the QueryDict to a mutable one
        request.POST['company_id'] = request.user.employee.company_id.pk
        form = EmployeeForm(request.user.employee.company_id, request.POST)
        if form.is_valid():
            employee = form.save(commit=False)
            user_taken = None
            if 'picture' in request.FILES:
                employee.picture = request.FILES['picture']
            if employee.degree:
                employee.sub_section_id = employee.degree.sub_section_id
                employee.section_id = employee.degree.sub_section_id.section_id
                employee.department_id =  employee.degree.sub_section_id.section_id.department_id
                employee.branch_id = employee.degree.sub_section_id.section_id.department_id.branch_id
            if form.cleaned_data['user_name'] and form.cleaned_data['password']:
                username = form.cleaned_data['user_name']
                password = form.cleaned_data['password']
                first_name = employee.first_name
                last_name = employee.last_name
                user = User(username=username, password=password, first_name=first_name, last_name=last_name)
                try:
                    user.save()
                    employee.user_id = user.id
                except:
                    messages.error(request, "حساب المستخدم الذى تم ادخالة موجود من قبل، لم نتمكن من حفظ البيان!")
                    user_taken = True
                    form = EmployeeForm(request.user.employee.company_id, request.POST)
            if not user_taken:
                employee.save()
                success_msg = 'تم اضافة "{}" بنجاح'.format(employee.first_name)
                messages.success(request, success_msg)
                # Emptying the form before rerendering it back
                form = EmployeeForm(request.user.employee.company_id)
        else: # Form was not valid
            # Spitting the errors coming from the form
            [messages.error(request, error[0]) for error in form.errors.values()]
        # Handling the "save and add another" button
        if 'save_and_add' in request.POST:
            save_and_add = True
        else:
            save_and_add = False
        context = {'table_title':'الموظفين', 'modal_title':'اضافة موظف جديد', 'save_and_add':save_and_add, 'form':form}
    else:   # Request is GET
        # Just passing an empty form to be rendered in case of GET
        try:
            # passing the company id to the form to filter on the current user company.
            form = EmployeeForm(request.user.employee.company_id)
            context = {'table_title':'الموظفين', 'modal_title':'اضافة موظف جديد', 'form':form}
        except: # Just in case the logged user is not tied to an employee account (i.e. doesn't have a company_id)
            messages.error(request, "لقد حدث خطأ ما، قد يكون هذا الحساب غير مسجل على شركة")
    try:    # Either GET or POST, We will render a table containing objects with company_id equals to user's company_id
        if by != '':
            employees = Employee.objects.filter(company_id=request.user.employee.company_id).order_by(by)
        else:
            employees = Employee.objects.filter(company_id=request.user.employee.company_id)
        context['employees'] = employees
    except: # Just in case the logged user is not tied to an employee account (i.e. doesn't have a company_id)
        messages.error(request, "لقد حدث خطأ ما، قد يكون هذا الحساب غير مسجل على شركة")
        return render(request, 'employees/employees_list.html')
    # Finally, and In all the cases, we will always render the same page to the user
    return render(request, 'employees/employees_list.html', context=context)

# this function is used to export the employees data from db to excel file.
def export_data(request):
    employee_resources = EmployeeResources()
    dataset = employee_resources.export()
    # response = HttpResponse(dataset.csv, content_type='text/csv')
    response = HttpResponse(dataset.xls, content_type='application/vnd.ms-excel')   # we can change the output file extention or type
    response['Content-Disposition'] = 'attachment; filename="employees.xls"'
    return response

# this function is used to import the employees data from excel file and insert them into db.
def employee_upload(request):
    # an empty list to fill later with the excel sheet header
    formHeader = list()
    # an empty list to fill later with the excel sheet rows
    formBody   = list()
    if request.method == 'POST':
        # calling the resource file we created to  get the employee from employee model.
        emp_resource = EmployeeResources()
        dataset = Dataset()
        if 'empFile' in request.FILES:      # file name comes from HTML page.
            new_employee = request.FILES['empFile']
            imported_data = dataset.load(new_employee.read())
            formHeader = imported_data.headers
            # start looping for the range of row count inside the excel sheet to get the rows
            for i in range(imported_data.height):
                formBody.append(imported_data[i])

            paginator = Paginator(formBody, 5) # Show 5 contacts per page
            page = request.GET.get('page')
            cases = paginator.get_page(page)
            # result = emp_resource.import_data(dataset, dry_run=True)  # Test the data import after importing
            # if not result.has_errors():
            #     emp_resource.import_data(dataset, dry_run=False)  # Actually import the data into db and save it.
        else:
            messages.error(request, 'No Such file, Or bad request.')
    myContext = {'formHeader':formHeader, 'formBody':formBody}
    return render(request, 'employees/employee_upload.html', myContext)

@login_required
def edit_employee(request, pk):
    try:
        employee = Employee.objects.get(pk=pk)
        if employee.company_id != request.user.employee.company_id:
            return HttpResponseForbidden("<h1>Access Denied! </h1>")
        if employee.is_active == False: #user trying to access the edit page of the inactive employee from browser url
            messages.error(request, 'هذا البيان غير قابل للتعديل!!')
            return redirect('employees:employees_list', by='')
        if request.method == 'POST':
            form = EmployeeForm(request.user.employee.company_id, request.POST, instance=employee)
            if form.is_valid():
                if 'picture' in request.FILES:
                    image = request.FILES['picture']
                    extension = image.name.split('.')[-1]
                    if extension not in ['bmp', 'gif', 'png', 'ico', 'jpg', 'jpeg', 'psd']:
                        msg = "ملف الصورة يجب أن يكون واحد من هذة الأنواع فقط: 'bmp', 'gif', 'png', 'ico', 'jpg', 'jpeg', 'psd'"
                        messages.error(request, msg)
                        return redirect('employees:employees_list', by='')
                employee = form.save(commit=False)
                user_taken = None
                if 'picture' in request.FILES:
                    employee.picture = request.FILES['picture']
                if employee.degree:
                    employee.sub_section_id = employee.degree.sub_section_id
                    employee.section_id = employee.degree.sub_section_id.section_id
                    employee.department_id =  employee.degree.sub_section_id.section_id.department_id
                    employee.branch_id = employee.degree.sub_section_id.section_id.department_id.branch_id
                if form.cleaned_data['user_name'] and form.cleaned_data['password'] and not employee.user:
                    username = form.cleaned_data['user_name']
                    password = form.cleaned_data['password']
                    first_name = employee.first_name
                    last_name = employee.last_name
                    user = User(username=username, password=password, first_name=first_name, last_name=last_name)
                    try:
                        user.save()
                        employee.user_id = user.id
                    except:
                        messages.error(request, "حساب المستخدم الذى تم ادخالة موجود من قبل، لم نتمكن من حفظ البيان!")
                        user_taken = True
                        form = EmployeeForm(request.user.employee.company_id, request.POST)
                if not user_taken:
                    employee.save()
                    success_msg = 'تم تعديل "{}" بنجاح'.format(employee.first_name)
                    messages.success(request, success_msg)
            else: # Form was not valid
                # Spitting the errors coming from the form
                [messages.error(request, error[0]) for error in form.errors.values()]
        else: # request method is GET
            if employee.user:

employees/templates/employees/contracts_list.html
{% extends "dashboard-viewdata.html" %}
{% load staticfiles %}
{% block table %}
<table class="table table-hover table-sm">
        <thead>
            <tr>
                <th class="pr-4" scope="col">م</th>
                <th scope="col">
                <a href={% url 'employees:contracts_list' by='name' %} class="text-white">
                    اسم العقد
                </a>
                </th>
                <th scope="col">تعديل</th>
                <th scope="col">حذف</th>
            </tr>
        </thead>
        <tbody>
            {% for contract in contracts %}
            <tr class="table-light" id="table-row" >
                    <td class="pr-4" scope="row">
                        {{ forloop.counter }}
                    </td>
                    <td>{{contract.name}}</td>
                    <td> <a href={% url 'employees:edit_contract' pk=contract.pk %}><img src={% static 'img/edit-icon.png' %} alt="edit"></a></td>
                    <td>
                        <a href="#" data-toggle="modal" data-target="#delete-modal-{{contract.pk}}">
                            <img src={% static 'img/delete-icon.png' %} alt="delete">
                        </a>
                    </td>
                    
            </tr>
            <div class="modal fade" id="delete-modal-{{contract.pk}}" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                    <div class=" modal-dialog modal modal-dialog-centered w-50 p-3" role="document">
                    <div class="modal-content alert">
                        <div class="modal-header">
                            <h3 class="modal-title" id="detailModalLabel">هل أنت متأكد؟</h3>
                        </div>
                            <div class="modal-body">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                                    <a type="button" class="btn btn-danger" href={% url 'employees:delete_contract' pk=contract.pk %}>نعم، احذف</a>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
        </tbody>
    </table> 
{% endblock table %}
        

employees/templates/employees/education_degrees_list.html
{% extends "dashboard-viewdata.html" %}
{% load staticfiles %}
{% block table %}
<table class="table table-hover table-sm">
        <thead>
            <tr>
                <th class="pr-4" scope="col">م</th>
                <th scope="col">
                        <a href={% url 'employees:education_degrees_list' by='name' %} class="text-white">
                            اسم الدرجة
                        </a>
                </th>
                <th scope="col">تعديل</th>
                <th scope="col">حذف</th>
            </tr>
        </thead>
        <tbody>
            {% for education_degree in education_degrees %}
            <tr class="table-light" id="table-row" >
                    <td class="pr-4" scope="row">
                        {{ forloop.counter }}
                    </td>
                    <td>{{education_degree.name}}</td>
                    <td> <a href={% url 'employees:edit_education_degree' pk=education_degree.pk %}><img src={% static 'img/edit-icon.png' %} alt="edit"></a></td>
                    <td>
                        <a href="#" data-toggle="modal" data-target="#delete-modal-{{education_degree.pk}}">
                            <img src={% static 'img/delete-icon.png' %} alt="delete">
                        </a>
                    </td>
                    
            </tr>
            <div class="modal fade" id="delete-modal-{{education_degree.pk}}" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                    <div class=" modal-dialog modal modal-dialog-centered w-50 p-3" role="document">
                    <div class="modal-content alert">
                        <div class="modal-header">
                            <h3 class="modal-title" id="detailModalLabel">هل أنت متأكد؟</h3>
                        </div>
                            <div class="modal-body">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                                    <a type="button" class="btn btn-danger" href={% url 'employees:delete_education_degree' pk=education_degree.pk %}>نعم، احذف</a>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
        </tbody>
    </table> 
{% endblock table %}
        

employees/templates/employees/genders_list.html
{% extends "dashboard-viewdata.html" %}
{% load staticfiles %}
{% block table %}
<table class="table table-hover table-sm">
        <thead>
            <tr>
                <th class="pr-4" scope="col">م</th>
                <th scope="col">
                <a href={% url 'employees:genders_list' by='name' %} class="text-white">
                    النوع
                </a>
                </th>
                <th scope="col">تعديل</th>
                <th scope="col">حذف</th>
            </tr>
        </thead>
        <tbody>
            {% for gender in genders %}
            <tr class="table-light" id="table-row" >
                    <td class="pr-4" scope="row">
                        {{ forloop.counter }}
                    </td>
                    <td>{{gender.name}}</td>
                    <td> <a href={% url 'employees:edit_gender' pk=gender.pk %}><img src={% static 'img/edit-icon.png' %} alt="edit"></a></td>
                    <td>
                        <a href="#" data-toggle="modal" data-target="#delete-modal-{{gender.pk}}">
                            <img src={% static 'img/delete-icon.png' %} alt="delete">
                        </a>
                    </td>
                    
            </tr>
            <div class="modal fade" id="delete-modal-{{gender.pk}}" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                    <div class=" modal-dialog modal modal-dialog-centered w-50 p-3" role="document">
                    <div class="modal-content alert">
                        <div class="modal-header">
                            <h3 class="modal-title" id="detailModalLabel">هل أنت متأكد؟</h3>
                        </div>
                            <div class="modal-body">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                                    <a type="button" class="btn btn-danger" href={% url 'employees:delete_gender' pk=gender.pk %}>نعم، احذف</a>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
        </tbody>
    </table> 
{% endblock table %}
        

employees/templates/employees/id_documents_list.html
{% extends "dashboard-viewdata.html" %}
{% load staticfiles %}
{% block table %}
<table class="table table-hover table-sm">
        <thead>
            <tr>
                <th class="pr-4" scope="col">م</th>
                <th scope="col">
                    <a href={% url 'employees:id_documents_list' by='name' %} class="text-white">
                        اسم وثيقة الهوية
                    </a>
                </th>
                <th scope="col">تعديل</th>
                <th scope="col">حذف</th>
            </tr>
        </thead>
        <tbody>
            {% for id_document in id_documents %}
            <tr class="table-light" id="table-row" >
                    <td class="pr-4" scope="row">
                        {{ forloop.counter }}
                    </td>
                    <td>{{id_document.name}}</td>
                    <td> <a href={% url 'employees:edit_id_document' pk=id_document.pk %}><img src={% static 'img/edit-icon.png' %} alt="edit"></a></td>
                    <td>
                        <a href="#" data-toggle="modal" data-target="#delete-modal-{{id_document.pk}}">
                            <img src={% static 'img/delete-icon.png' %} alt="delete">
                        </a>
                    </td>
                    
            </tr>
            <div class="modal fade" id="delete-modal-{{id_document.pk}}" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                    <div class=" modal-dialog modal modal-dialog-centered w-50 p-3" role="document">
                    <div class="modal-content alert">
                        <div class="modal-header">
                            <h3 class="modal-title" id="detailModalLabel">هل أنت متأكد؟</h3>
                        </div>
                            <div class="modal-body">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                                    <a type="button" class="btn btn-danger" href={% url 'employees:delete_id_document' pk=id_document.pk %}>نعم، احذف</a>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
        </tbody>
    </table> 
{% endblock table %}
        

employees/templates/employees/military_status_list.html
{% extends "dashboard-viewdata.html" %}
{% load staticfiles %}
{% block table %}
<table class="table table-hover table-sm">
        <thead>
            <tr>
                <th class="pr-4" scope="col">م</th>
                <th scope="col">
                <a href={% url 'employees:military_status_list' by='name' %} class="text-white">
                    اسم الموقف من التجنيد
                </a>
                </th>
                <th scope="col">تعديل</th>
                <th scope="col">حذف</th>
            </tr>
        </thead>
        <tbody>
            {% for military_status in military_status_list %}
            <tr class="table-light" id="table-row" >
                    <td class="pr-4" scope="row">
                        {{ forloop.counter }}
                    </td>
                    <td>{{military_status.name}}</td>
                    <td> <a href={% url 'employees:edit_military_status' pk=military_status.pk %}><img src={% static 'img/edit-icon.png' %} alt="edit"></a></td>
                    <td>
                        <a href="#" data-toggle="modal" data-target="#delete-modal-{{military_status.pk}}">
                            <img src={% static 'img/delete-icon.png' %} alt="delete">
                        </a>
                    </td>
                    
            </tr>
            <div class="modal fade" id="delete-modal-{{military_status.pk}}" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                    <div class=" modal-dialog modal modal-dialog-centered w-50 p-3" role="document">
                    <div class="modal-content alert">
                        <div class="modal-header">
                            <h3 class="modal-title" id="detailModalLabel">هل أنت متأكد؟</h3>
                        </div>
                            <div class="modal-body">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                                    <a type="button" class="btn btn-danger" href={% url 'employees:delete_military_status' pk=military_status.pk %}>نعم، احذف</a>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
        </tbody>
    </table> 
{% endblock table %}
        

employees/templates/employees/religions_list.html
{% extends "dashboard-viewdata.html" %}
{% load staticfiles %}
{% block table %}
<table class="table table-hover table-sm">
        <thead>
            <tr>
                <th class="pr-4" scope="col">م</th>
                <th scope="col">
                    <a href={% url 'employees:religions_list' by='name' %} class="text-white">
                        الديانة
                    </a>
                </th>
                <th scope="col">تعديل</th>
                <th scope="col">حذف</th>
            </tr>
        </thead>
        <tbody>
            {% for religion in religions %}
            <tr class="table-light" id="table-row" >
                    <td class="pr-4" scope="row">
                        {{ forloop.counter }}
                    </td>
                    <td>{{religion.name}}</td>
                    <td> <a href={% url 'employees:edit_religion' pk=religion.pk %}><img src={% static 'img/edit-icon.png' %} alt="edit"></a></td>
                    <td>
                        <a href="#" data-toggle="modal" data-target="#delete-modal-{{religion.pk}}">
                            <img src={% static 'img/delete-icon.png' %} alt="delete">
                        </a>
                    </td>
                    
            </tr>
            <div class="modal fade" id="delete-modal-{{religion.pk}}" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                    <div class=" modal-dialog modal modal-dialog-centered w-50 p-3" role="document">
                    <div class="modal-content alert">
                        <div class="modal-header">
                            <h3 class="modal-title" id="detailModalLabel">هل أنت متأكد؟</h3>
                        </div>
                            <div class="modal-body">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                                    <a type="button" class="btn btn-danger" href={% url 'employees:delete_religion' pk=religion.pk %}>نعم، احذف</a>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
        </tbody>
    </table> 
{% endblock table %}
        

employees/templates/employees/social_status_list.html
{% extends "dashboard-viewdata.html" %}
{% load staticfiles %}
{% block table %}
<table class="table table-hover table-sm">
        <thead>
            <tr>
                <th class="pr-4" scope="col">م</th>
                <th scope="col">
                <a href={% url 'employees:social_status_list' by='name' %} class="text-white">
                    اسم الحالة الاجتماعية
                </a>
                </th>
                <th scope="col">تعديل</th>
                <th scope="col">حذف</th>
            </tr>
        </thead>
        <tbody>
            {% for social_status in social_status_list %}
            <tr class="table-light" id="table-row" >
                    <td class="pr-4" scope="row">
                        {{ forloop.counter }}
                    </td>
                    <td>{{social_status.name}}</td>
                    <td> <a href={% url 'employees:edit_social_status' pk=social_status.pk %}><img src={% static 'img/edit-icon.png' %} alt="edit"></a></td>
                    <td>
                        <a href="#" data-toggle="modal" data-target="#delete-modal-{{social_status.pk}}">
                            <img src={% static 'img/delete-icon.png' %} alt="delete">
                        </a>
                    </td>
                    
            </tr>
            <div class="modal fade" id="delete-modal-{{social_status.pk}}" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                    <div class=" modal-dialog modal modal-dialog-centered w-50 p-3" role="document">
                    <div class="modal-content alert">
                        <div class="modal-header">
                            <h3 class="modal-title" id="detailModalLabel">هل أنت متأكد؟</h3>
                        </div>
                            <div class="modal-body">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                                    <a type="button" class="btn btn-danger" href={% url 'employees:delete_social_status' pk=social_status.pk %}>نعم، احذف</a>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
        </tbody>
    </table> 
{% endblock table %}
        