home/urls.py
from django.conf.urls import url
from home import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.landing, name='landing_page'),
    url(r'^dashboard/', views.dashboard, name='dashboard'),
    url(r'^login/', views.user_login, name='login'),
    url(r'^logout/', views.user_logout, name='logout'),
    
]

mashreq_hr_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from mashreq_hr_project import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls'), name="home"),
    url(r'^$', views.redirect, name='redirect'),
    url(r'^company/', include('companies.urls'), name='companies'),
    url(r'^employees/', include('employees.urls'), name='employees'),
    url(r'attendance/', include('attendance.urls'), name='attendance'),
    url(r'payroll/', include('payroll.urls'), name='payroll'),
    url(r'banks/', include('banks.urls'), name='banks'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Admin site global customizations
admin.site.site_header = 'Mashreq Arabia - HR'
admin.site.site_title = 'Mashreq Arabia - HR'

payroll/urls.py
from django.conf.urls import url
from payroll import views

app_name = 'payroll'

urlpatterns = [
    url(r'^salaries/(?P<by>[a-zA-Z_]*)$', views.salaries_list, name='salaries_list'),
    url(r'^delete/salary/(?P<pk>\d+)/$', views.delete_salary, name='delete_salary'),
    url(r'^edit/salary/(?P<pk>\d+)/$', views.edit_salary, name='edit_salary'),
    url(r'^finalize/salary/(?P<pk>\d+)/$', views.finalize_salary, name='finalize_salary'),
    url(r'^recalculate/salary/(?P<pk>\d+)/$', views.recalculate_salary, name='recalculate_salary'),
    url(r'^copy/salaries', views.copy_salaries, name='copy_salaries'),
    url(r'^send/payslips', views.send_payslips, name='send_payslips'),
    url(r'^salary_element_types/(?P<by>[a-zA-Z_]*)$', views.salary_element_types_list, name='salary_element_types_list'),
    url(r'^delete/salary_element_type/(?P<pk>\d+)/$', views.delete_salary_element_type, name='delete_salary_element_type'),
    url(r'^edit/salary_element_type/(?P<pk>\d+)/$', views.edit_salary_element_type, name='edit_salary_element_type'),
    url(r'^insurance_rules/(?P<by>[a-zA-Z_]*)$', views.insurance_rules_list, name='insurance_rules_list'),
    url(r'^delete/insurance_rule/(?P<pk>\d+)/$', views.delete_insurance_rule, name='delete_insurance_rule'),
    url(r'^edit/insurance_rule/(?P<pk>\d+)/$', views.edit_insurance_rule, name='edit_insurance_rule'),
    url(r'^custom_rules/(?P<by>[a-zA-Z_]*)$', views.custom_rules_list, name='custom_rules_list'),
    url(r'^delete/custom_rule/(?P<pk>\d+)/$', views.delete_custom_rule, name='delete_custom_rule'),
    url(r'^edit/custom_rule/(?P<pk>\d+)/$', views.edit_custom_rule, name='edit_custom_rule'),
    url(r'^tax_rules/(?P<by>[a-zA-Z_]*)$', views.tax_rules_list, name='tax_rules_list'),
    url(r'^delete/tax_rule/(?P<pk>\d+)/$', views.delete_tax_rule, name='delete_tax_rule'),
    url(r'^edit/tax_rule/(?P<pk>\d+)/$', views.edit_tax_rule, name='edit_tax_rule'),
]

payroll/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.conf import settings as s
from payroll.pdf_email_helper import Mailer
from payroll.sending_report import SendingReport
from payroll.models import Salary, SalaryElementType, InsuranceRule, CustomPythonRule, TaxRule
from payroll.forms import (SalaryForm, SalaryElementFormSet, SalaryElementTypeForm, InsuranceRuleForm,
                           CustomPythonRuleForm, TaxRuleForm, TaxSectionFormSet, PayslipsForm, CopySalariesForm)
from employees.models import Employee
from pdfkit import from_string as convert_to_pdf
from time import sleep
from threading import Thread
import os
from django.http import HttpResponseForbidden

@login_required
def salaries_list(request, by):
    context = {'table_title':'المرتبات', 'modal_title':'اضافة بيان مرتب جديد', 'formset_title':'بنود اضافية'}
    if request.method == "POST":
        form = SalaryForm(request.user.employee.company_id, request.POST)
        formset = SalaryElementFormSet(request.POST)
        formset.can_delete = False
        formset_queryset = SalaryElementType.objects.filter(company_id=request.user.employee.company_id)
        for f in formset.forms:
            f.fields['type_id'].queryset=formset_queryset
        if form.is_valid():
            salary = form.save(commit=False)
            formset = SalaryElementFormSet(request.POST, instance=salary)
            formset.can_delete = False
            for f in formset.forms:
                f.fields['type_id'].queryset=formset_queryset
            if formset.is_valid():
                salary.save()
                formset.save()
                success_msg = 'تم اضافة "{}" بنجاح'.format(str(salary))
                messages.success(request, success_msg)
                # Emptying the form and formset before rerendering them back
                form = SalaryForm(request.user.employee.company_id)
                formset = SalaryElementFormSet()
                formset.can_delete = False
                for f in formset.forms:
                    f.fields['type_id'].queryset=formset_queryset
            else: # formset was not valid
                for error_dict in formset.errors:
                    [messages.error(request, error[0]) for error in error_dict.values()]
        else: # Form was not valid
            # Spitting the errors coming from the form
            [messages.error(request, error[0]) for error in form.errors.values()]
        # Handling the "save and add another" button
        if 'save_and_add' in request.POST:
            save_and_add = True
        else:
            save_and_add = False
        context['save_and_add'] = save_and_add
    else:   # Request is GET
        try:
            # Just passing empty form and formset to be rendered in case of GET
            form = SalaryForm(request.user.employee.company_id)
            formset = SalaryElementFormSet()
            formset.can_delete = False
            formset_queryset = SalaryElementType.objects.filter(company_id=request.user.employee.company_id)
            for f in formset.forms:
                f.fields['type_id'].queryset=formset_queryset
        except: # Just in case the logged user is not tied to an employee account (i.e. doesn't have a company_id)
            messages.error(request, "لقد حدث خطأ ما، قد يكون هذا الحساب غير مسجل على شركة")
            return render(request, 'payroll/salaries_list.html')
    # Either GET or POST, We will render a table containing objects with company_id equals to user's company_id
    if by != '':
        salaries = Salary.objects.filter(employee_id__company_id=request.user.employee.company_id).order_by(by)
    else:
        salaries = Salary.objects.filter(employee_id__company_id=request.user.employee.company_id)
    context['salaries'] = salaries
    context['form'] = form
    context['formset'] = formset
    # Finally, and In all the cases, we will always render the same page to the user
    return render(request, 'payroll/salaries_list.html', context=context)

@login_required
def delete_salary(request, pk):
    try:
        salary = Salary.objects.get(pk=pk)
        if salary.employee_id.company_id != request.user.employee.company_id:
            return HttpResponseForbidden("<h1>Access Denied! </h1>")
        if salary.is_final:
            messages.error(request, 'هذا البيان نهائي و لا يمكن حذفة!')
            return redirect('payroll:salaries_list', by='')
        salary.delete()
        success_msg = 'تم حذف "{}" بنجاح'.format(str(salary))
        messages.success(request, success_msg)
    except:
        error_msg = 'لم يتم الحذف المطلوب، خطأ ما قد حدث'
        messages.error(request, error_msg)
    return redirect('payroll:salaries_list', by='')

@login_required
def edit_salary(request, pk):
    try:
        salary = Salary.objects.get(pk=pk)
        if salary.employee_id.company_id != request.user.employee.company_id:
            return HttpResponseForbidden("<h1>Access Denied! </h1>")
        if salary.is_final:
            messages.error(request, 'هذا البيان نهائي و لا يمكن تعديلة!')
            return redirect('payroll:salaries_list', by='')
        formset_queryset = SalaryElementType.objects.filter(company_id=request.user.employee.company_id)
        context = {'table_title':'المرتبات', 'modal_title':'تعديل بيان المرتب', 'formset_title':'بنود المرتب'}
        if request.method == 'POST':
            form = SalaryForm(request.user.employee.company_id, request.POST, instance=salary)
            formset = SalaryElementFormSet(request.POST, instance=salary)
            for f in formset.forms:
                f.fields['type_id'].queryset=formset_queryset
                f.fields['DELETE'].label = 'حذف'
            if form.is_valid() and formset.is_valid():
                salary = form.save()
                formset.save()
                success_msg = 'تم تعديل "{}" بنجاح'.format(str(salary))
                messages.success(request, success_msg)
            else: # Form or/and formset were not valid
                # Spitting the errors coming from the form and formset
                [messages.error(request, error[0]) for error in form.errors.values()]
                for error_dict in formset.errors:
                    [messages.error(request, error[0]) for error in error_dict.values()]
        else: # request method is GET
            form = SalaryForm(request.user.employee.company_id, instance=salary)
            formset = SalaryElementFormSet(instance=salary)
            for f in formset.forms:
                f.fields['type_id'].queryset=formset_queryset
                f.fields['DELETE'].label = 'حذف'
            modal_close_url = 'payroll:salaries_list'
            context['modal_close_url'] = modal_close_url
            context['editing'] = True
            try:
                salaries = Salary.objects.filter(employee_id__company_id=request.user.employee.company_id)
                context['salaries'] = salaries
                context['form'] = form
                context['formset'] = formset
            except: # Just in case the logged user is not tied to an employee account (i.e. doesn't have a company_id)
                messages.error(request, "لقد حدث خطأ ما، قد يكون هذا الحساب غير مسجل على شركة")
            return render(request, 'payroll/salaries_list.html', context=context)
    except:
        error_msg = 'لم يتم العثور على البيان المطلوب، قد يكون قد تم حذفة من قبل'     
        messages.error(request, error_msg)
    return redirect('payroll:salaries_list', by='')

@login_required
def finalize_salary(request, pk):
    try:
        salary = Salary.objects.get(pk=pk)
        if salary.employee_id.company_id != request.user.employee.company_id:
            return HttpResponseForbidden("<h1>Access Denied! </h1>")
        salary.is_final = True
        salary.save()
        success_msg = 'البيان {} أصبح الان نسخة نهائية'.format(str(salary))
        messages.success(request, success_msg)
    except:
        error_msg = 'لم يتم التعديل المطلوب، خطأ ما قد حدث'
    return redirect('payroll:salaries_list', by='')

@login_required
def recalculate_salary(request, pk):
    try:
        salary = Salary.objects.get(pk=pk)
        if salary.employee_id.company_id != request.user.employee.company_id:
            return HttpResponseForbidden("<h1>Access Denied! </h1>")
        if salary.is_final:
            error_msg = 'هذا البيان نهائي و لا يمكن تعديلة!'
            messages.error(request, error_msg)
            return redirect('payroll:salaries_list', by='')
        salary.populate_employee_deducted_days()
        salary.save()
        success_msg = 'تم اعادة حساب و تحديث البيان "{}" بنجاح'.format(str(salary))
        messages.success(request, success_msg)
    except:
        error_msg = 'لم يتم التحديث المطلوب، خطأ ما قد حدث'
        messages.error(request, error_msg)
    return redirect('payroll:salaries_list', by='')

@login_required
def copy_salaries(request):
    if request.method == 'POST':
        form = CopySalariesForm(request.POST)
        if form.is_valid():
            from_month = form.cleaned_data['from_month']
            from_year = form.cleaned_data['from_year']
            to_month = form.cleaned_data['to_month']
            to_year = form.cleaned_data['to_year']

            salaries = Salary.objects.filter(year=from_year).filter(month=from_month)
            successes = 0
            failures = 0
            for salary in salaries:
                salary.pk = None
                salary.month = to_month
                salary.year = to_year
                salary.is_final = False
                try:
                    salary.clean()                    
                    salary.save()
                    successes += 1
                except:
                    failures += 1

payroll/templates/payroll/custom_rules_list.html
{% extends "dashboard-viewdata.html" %}
{% load staticfiles %}
{% block table %}
<table class="table table-hover table-sm">
        <thead>
            <tr>
                <th class="pr-4" scope="col">م</th>
                <th scope="col">
                <a href={% url 'payroll:custom_rules_list' by='name' %} class="text-white">
                    اسم القاعدة
                </a>
                </th>
                <th scope="col">
                <a href={% url 'payroll:custom_rules_list' by='taxable' %} class="text-white">
                    خاضعة للضريبة؟
                </a>
                </th>
                <th scope="col">تعديل</th>
                <th scope="col">حذف</th>
            </tr>
        </thead>
        <tbody>
            {% for custom_rule in custom_rules %}
            <tr class="table-light" id="table-row" >
                    <td class="pr-4" scope="row" data-toggle="modal" data-target="#detail-modal-{{custom_rule.pk}}">
                        {{ forloop.counter }}
                    </td>
                    <td data-toggle="modal" data-target="#detail-modal-{{custom_rule.pk}}">{{custom_rule.name}}</td>
                    {% if custom_rule.taxable %}
                    <td data-toggle="modal" data-target="#detail-modal-{{custom_rule.pk}}">نعم</td>
                    {% else %}
                    <td data-toggle="modal" data-target="#detail-modal-{{custom_rule.pk}}">لا</td>
                    {% endif %}
                    <td> <a href={% url 'payroll:edit_custom_rule' pk=custom_rule.pk %}><img src={% static 'img/edit-icon.png' %} alt="edit"></a></td>
                    <td>
                        <a href="#" data-toggle="modal" data-target="#delete-modal-{{custom_rule.pk}}">
                            <img src={% static 'img/delete-icon.png' %} alt="delete">
                        </a>
                    </td>
                    
            </tr>
            <!--Detail Modal -->
            <div class="modal fade" id="detail-modal-{{custom_rule.pk}}" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                <div class="modal-dialog modal modal-dialog-centered p-3" role="document">
                <div class="modal-content p-3">
                    <div class="modal-header">
                        <h3 class="modal-title" id="detailModalLabel">تفاصيل القاعدة:</h3>
                    </div>
                        <div id="detail-list" class="modal-body">
                            <ul class="list-group">
                                <li class="list-group-item list-group-item-primary d-flex justify-content-between align-items-center">
                                    اسم القاعدة:    
                                    {{custom_rule.name}}
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
   
                                        <div class="container">
                                                <div class="col">
                                                    تعريف القاعدة: 
                                                </div>
                                                <div class="col" style="background: #fdf6e3;float: left;direction: ltr; font-size: 0.65em; text-align: left; padding-top: 1em; border-radius: 0.1em;">
                                                        {% spaceless %}    
                                                    <pre>
                                                                <code style="color: #b52a00;">{{custom_rule.rule_definition}}</code>
                                                        </pre>
                                                        {% endspaceless %}
                                            </div>


                                        </div>
                                    </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    خاضعة للضريبة:
                                    {% if custom_rule.taxable %}
                                    <span class="badge badge-success badge-pill">نعم</span>
                                    {% else %}
                                    <span class="badge badge-danger badge-pill">لا</span>
                                    {% endif %}
                                </li>
                            </ul>
                            <div id="detail-buttons">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                                    <a type="button" class="btn btn-primary" href={% url 'payroll:edit_custom_rule' pk=custom_rule.pk %}>تعديل</a>
                                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete-modal-{{custom_rule.pk}}">حذف</button>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="delete-modal-{{custom_rule.pk}}" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                    <div class=" modal-dialog modal modal-dialog-centered w-50 p-3" role="document">
                    <div class="modal-content alert">
                        <div class="modal-header">
                            <h3 class="modal-title" id="detailModalLabel">هل أنت متأكد؟</h3>
                        </div>
                            <div class="modal-body">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                                    <a type="button" class="btn btn-danger" href={% url 'payroll:delete_custom_rule' pk=custom_rule.pk %}>نعم، احذف</a>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
        </tbody>
    </table> 
    <hr>
    <div class="col p-5" style="text-align: right; direction: rtl;">
            <h3>كيفية تعريف قاعدة مخصصة باستخدام لغة بايثون:</h3>
            <p>
                يمكنك تعريف قاعدة خصم / إضافة مخصصة هنا باستخدام لغة بايثون
    
            </p>
            <p>
                لديك المتغيرات التالية متاحة للاستخدام:
    
            </p>
            <ul>
                <li>
                   <b><code>basic:</code></b>  هذا هو الراتب الأساسي للموظف.
                </li>
                <li>
                   <b><code>variable:</code></b>  هذا هو الراتب المتغير للموظف.
                </li>
                <li>
                    <b><code>d_days:</code></b>هذه هي عدد الأيام التي يجب خصمها للموظف في هذا الشهر
                    بسبب غيابه أو بسبب قواعد أخرى للحضور تنطوي على أيام خصم.
    
                </li>
                <li>
                        <b><code> grs:</code></b>(بدون "o")
                        الراتب الإجمالي و الذى يساوي الراتب الأساسي + الراتب المتغير + أي بدلات / مكافآت / حوافز إضافية مضافة.
    
                </li>
            </ul>
            <p>
    
            </p>
            بعد حساب المعادلة الخاصة بك ، يجب عليك تخزين المبلغ المطلوب ليتم إضافته / خصمه في متغير يسمى <b><code>amount</code></b>.
            إذا كانت قيمة <b><code>amount</code></b> موجبة ، فسيتم إضافة المبلغ إلى المرتب الصافي للموظف.
            وإذا كان سالبة ، سيتم خصمها.
            
            
            <h4>مثال:</h4>
    
            <div class="container">
            <div class="col" style="background: #fdf6e3;float: left;direction: ltr; font-size: 0.75em; text-align: left; padding-top: 1em; border-radius: 0.1em;">
            <pre>
            <code style="color: #b52a00;">
            if basic <= 5000:
                extra_deduction = -250
            else:
                extra_deduction = -500
            amount = extra_deduction
            </code>
            </pre>
        </div>
                <br>
    <p>
        تأكد ان الكود المكتوب يطابق قواعد لغة البايثون
    </p>
    
            </div>
            
            </div>
{% endblock table %}


        
        

payroll/templates/payroll/insurance_rules_list.html
{% extends "dashboard-viewdata.html" %}
{% load staticfiles %}
{% block table %}
<table class="table table-hover table-sm">
        <thead>
            <tr>
                <th class="pr-4" scope="col">م</th>
                <th scope="col">
                <a href={% url 'payroll:insurance_rules_list' by='name' %} class="text-white">
                    اسم القاعدة
                </a>
                </th>
                <th scope="col">تعديل</th>
                <th scope="col">حذف</th>
            </tr>
        </thead>
        <tbody>
            {% for insurance_rule in insurance_rules %}
            {% if insurance_rule.company_id == user.employee.company_id %}
            <tr class="table-light" id="table-row" >
            {% else %}
            <tr class="table-success" id="table-row" >
            {% endif %}
                    <td class="pr-4" scope="row" data-toggle="modal" data-target="#detail-modal-{{insurance_rule.pk}}">
                        {{ forloop.counter }}
                    </td>
                    <td data-toggle="modal" data-target="#detail-modal-{{insurance_rule.pk}}">{{insurance_rule.name}}</td>
                    {% if insurance_rule.company_id == user.employee.company_id %}
                    <td> <a href={% url 'payroll:edit_insurance_rule' pk=insurance_rule.pk %}><img src={% static 'img/edit-icon.png' %} alt="edit"></a></td>
                    <td>
                        <a href="#" data-toggle="modal" data-target="#delete-modal-{{insurance_rule.pk}}">
                            <img src={% static 'img/delete-icon.png' %} alt="delete">
                        </a>
                    </td>
                    {% else %}
                    <td> <a href="#"><img src={% static 'img/edit-icon.png' %} alt="edit"></a></td>
                    <td>
                        <a href="#">
                            <img src={% static 'img/delete-icon.png' %} alt="delete">
                        </a>
                    </td>
                    {% endif %}
            </tr>
            <!--Detail Modal -->
            <div class="modal fade" id="detail-modal-{{insurance_rule.pk}}" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                <div class="modal-dialog modal modal-dialog-centered p-3" role="document">
                <div class="modal-content p-3">
                    <div class="modal-header">
                        <h3 class="modal-title" id="detailModalLabel">تفاصيل القاعدة:</h3>
                    </div>
                        <div id="detail-list" class="modal-body">
                            <ul class="list-group">
                                {% if insurance_rule.company_id == user.employee.company_id %}
                                <li class="list-group-item list-group-item-primary d-flex justify-content-between align-items-center">
                                {% else %}
                                <li class="list-group-item list-group-item-success d-flex justify-content-between align-items-center">
                                {% endif %}
                                    اسم القاعدة:    
                                    {{insurance_rule.name}}
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    نسبة الخصم على الراتب الاساسي:    
                                    <span class="badge badge-primary badge-pill">{{insurance_rule.basic_deduction_percentage}}%</span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    نسبة الخصم على الراتب المتغير:    
                                    <span class="badge badge-primary badge-pill">{{insurance_rule.variable_deduction_percentage}}%</span>
                                  
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    الحد الأقصي للراتب الأساسي التأميني: 
                                    <span class="badge badge-primary badge-pill">{{insurance_rule.maximum_insurable_basic_salary}}</span>

                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    الحد الأقصي للراتب المتغير التأميني:
                                    <span class="badge badge-primary badge-pill">{{insurance_rule.maximum_insurable_variable_salary}}</span>
                                </li>
                            </ul>
                            <div id="detail-buttons">
                                {% if insurance_rule.company_id == user.employee.company_id %}
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                                <a type="button" class="btn btn-primary" href={% url 'payroll:edit_insurance_rule' pk=insurance_rule.pk %}>تعديل</a>
                                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete-modal-{{insurance_rule.pk}}">حذف</button>
                                {% else %}
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                                {% endif %}
                                </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="delete-modal-{{insurance_rule.pk}}" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                    <div class=" modal-dialog modal modal-dialog-centered w-50 p-3" role="document">
                    <div class="modal-content alert">
                        <div class="modal-header">
                            <h3 class="modal-title" id="detailModalLabel">هل أنت متأكد؟</h3>
                        </div>
                            <div class="modal-body">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                                    <a type="button" class="btn btn-danger" href={% url 'payroll:delete_insurance_rule' pk=insurance_rule.pk %}>نعم، احذف</a>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
        </tbody>
    </table> 

{% endblock table %}


        
        

payroll/templates/payroll/salary_element_types_list.html
{% extends "dashboard-viewdata.html" %}
{% load staticfiles %}
{% block table %}
<table class="table table-hover table-sm">
        <thead>
            <tr>
                <th class="pr-4" scope="col">م</th>
                <th scope="col">
                        <a href={% url 'payroll:salary_element_types_list' by='name' %} class="text-white">
                        اسم البند
                        </a>
                </th>
                <th scope="col">
                        <a href={% url 'payroll:salary_element_types_list' by='element_type' %} class="text-white">
                            نوعه
                        </a>
                </th>
                <th scope="col">
                        <a href={% url 'payroll:salary_element_types_list' by='taxable' %} class="text-white">
                        خاضع للضريبة؟
                        </a>
                </th>
                <th scope="col">تعديل</th>
                <th scope="col">حذف</th>
            </tr>
        </thead>
        <tbody>
            {% for salary_element_type in salary_element_types %}
            <tr class="table-light" id="table-row" >
                    <td class="pr-4" scope="row">
                        {{ forloop.counter }}
                    </td>
                    <td>{{salary_element_type.name}}</td>
                    {% if salary_element_type.element_type == 'addition' %}
                    <td>اضافة</td>
                    {% elif  salary_element_type.element_type == 'deduction' %}
                    <td>خصم</td>
                    {% endif %}
                    {% if salary_element_type.taxable %}
                    <td>نعم</td>
                    {% else %}
                    <td>لا</td>
                    {% endif %}
                    <td> <a href={% url 'payroll:edit_salary_element_type' pk=salary_element_type.pk %}><img src={% static 'img/edit-icon.png' %} alt="edit"></a></td>
                    <td>
                        <a href="#" data-toggle="modal" data-target="#delete-modal-{{salary_element_type.pk}}">
                            <img src={% static 'img/delete-icon.png' %} alt="delete">
                        </a>
                    </td>
                    
            </tr>
            <div class="modal fade" id="delete-modal-{{salary_element_type.pk}}" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                    <div class=" modal-dialog modal modal-dialog-centered w-50 p-3" role="document">
                    <div class="modal-content alert">
                        <div class="modal-header">
                            <h3 class="modal-title" id="detailModalLabel">هل أنت متأكد؟</h3>
                        </div>
                            <div class="modal-body">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                                    <a type="button" class="btn btn-danger" href={% url 'payroll:delete_salary_element_type' pk=salary_element_type.pk %}>نعم، احذف</a>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
        </tbody>
    </table> 
{% endblock table %}
        